### ISSUE TITLE
not an issue - a thanks!

### ISSUE THREAD

**Issue by peter-mouland** [mightyiam/eslint-failing-rules#24]
Exactly what I needed - just trying to update 4 or 5 repos to airbnb eslint rules and needed to see which rules were failing to i could ignore them for now (and enable them one by one).

This worked 1st try to output the rules and the ignore flag. cheers!

```js
const eslint = require('eslint');
const getFailing = require('eslint-failing-rules');
const failing = getFailing(eslint, ['**/*.js']);
console.log(failing.sort().map((rule) => `"${rule}": 0`).join(`,
`));
```

**Comment by mightyiam** [comment]
Thanks. You know, I've been writing open source for a while and this is the first comment of this kind that I remember getting.

BTW, there's this:
https://github.com/mightyiam/eslint-failing-rules-off-config/
and this:
https://github.com/mightyiam/setup-eslint/
